spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    Exposed: DEBUG