spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:log4jdbc:mysql://localhost:3306/myreact?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver