#spring:
#  kafka:
#    consumer:
#      group-id: qqqq
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    bootstrap-servers: localhost:9092


kafka:
  server: localhost:9092
  consumer:
    groupId: foo